### PR TITLE
chore(evm): update FluxLayerZeroOracle interface

### PR DESCRIPTION
**Pull request by jamesondh**

### CODE REVIEW

**Comment by FranklinWaller** [comment]
Does this work? Seems like a lot of interface changes which are not compatible with the current used values (In the WebSocket part)

**Comment by jamesondh** [comment]
I tested with the new contract interface and successfully transmitted to a destination chain, can you also confirm @mennatabuelnaga ?

**Review by mennatabuelnaga — APPROVED** [review]
Tested it on Ropsten and it works great.

**Comment by FranklinWaller** [comment]
Awesome! Lgm!

**Pull request merged**
